### PR TITLE
Create Multiple_OCPBUGs_install_failure.json

### PR DESCRIPTION
**Pull request by jaybeeunix**
First take at something capturing what we talked about in the handover mtg.

### CODE REVIEW

**Comment by bdematte** [comment]
Would be good to include a parameter to allow tracking of the bugs by the customer (to be able to know when it is resolved and can be retried)

**Comment by aweiteka** [comment]
@arendej please review

**Review by arendej — APPROVED** [review]
lgtm, thank you

**Review by aweiteka — APPROVED** [review]

**Comment by aweiteka** [comment]
lgtm

**Pull request merged**
