### PR TITLE
Adds new scheduled chaos testing messaging.

### PR DESCRIPTION
**Pull request by iamkirkbater**
Adds a new template for scheduled chaos testing for customers to make the process of putting a cluster into LS easier for on-call SREs who are getting a "scheduled" ticket for this.

### CODE REVIEW

**Comment by iamkirkbater** [comment]
Not sure if we want to reference anything else in this template like the guidelines, and approval process since by the time the cluster is being put into Limited Support the customer should already have agreed to the guidelines and it should already be approved. I'm open to make those changes if we feel like we need to.

**Comment by geowa4** [comment]
Will there be a corresponding PR to https://github.com/openshift/ops-sop/blob/master/v4/howto/limited-support.md?plain=1?

**Pull request merged**
