### PR TITLE
Remove duplicate _tags and update SOP backrefs

### PR DESCRIPTION
**Pull request by geowa4**
This change removes duplicate SOP backreferences in _tags and applies some programmatic formatting. The code to do this can be found here: https://github.com/geowa4/servicelogger/pull/27.

[OSD-21264](https://issues.redhat.com//browse/OSD-21264)

### CODE REVIEW

**Comment by geowa4** [comment]
The test failures are for broken links in files that are not changed in this PR. I'll report this back to the owners of that change, but I don't think it should block this PR.

**Comment by bmeng** [comment]
seems the test failures are for other files... weird
/lgtm
/approve

**Comment by bmeng** [comment]
without the test pass, can we merge the change?
maybe we need to remove those broken links from the repo?

**Comment by bmeng** [comment]
should be good to merge now

**Pull request merged**
