### PR TITLE
Change wording of SL to remove SRE responsibility for deleting cluster

### PR DESCRIPTION
**Pull request by dakotalongRH**
Change wording of SL so that customer knows they need to delete their cluster and that it's not SRE responsibility.

https://issues.redhat.com/browse/OSD-18891

### CODE REVIEW

**Comment by dakotalongRH** [comment]
Seems like prow is failing on https://access.redhat.com/documentation/en-us/red_hat_openshift_service_on_aws/4/html/builds/setting-up-trusted-ca but that link is not part of this PR

**Review by fahlmant — APPROVED** [review]
/lgtm

**Pull request merged**
