### PR TITLE
OSD-7961 - Add notify-group script to send bulk servicelogs.

### PR DESCRIPTION
**Pull request by tnierman**
Adds stopgap solution for https://issues.redhat.com/browse/OSD-7691 until a more feature-complete ocm/osdctl plugin is created.

### CODE REVIEW

**Comment by csheremeta** [comment]
cc @c-e-brumm

**Comment by c-e-brumm** [comment]
@bdematte or @csheremeta can one of you please review the bash?

**Comment by csheremeta** [comment]
/lgtm
Sorry for delay!

**Pull request merged**
