### PR TITLE
OSD-13047 add example tags

### PR DESCRIPTION
**Pull request by feichashao**
For easier github/local searching, we can add tags to the template files, so that it can be searched in multiple dimensions.

This PR adds the `t_network` and `t_config` tags for example. We can add more tags to the template files in the future.

### CODE REVIEW

**Review by fahlmant — CHANGES_REQUESTED** [review]
I believe this will break posts to OCM since the api validates the JSON passed to it

**Comment by feichashao** [comment]
> I believe this will break posts to OCM since the api validates the JSON passed to it
@fahlmant  Thanks for reviewing! 

The [API schema](https://api.openshift.com/?urls.primaryName=Service%20logs#/default/post_api_service_logs_v1_cluster_logs) is different with the templates, posting the JSON to API directly shouldn't work.  My assumption is we always use `osdctl servicelog post` to send the request, and osdctl will only parse those fields it needed, ignoring `_tags`.
https://github.com/openshift/osdctl/blob/115f5f5b8abea2956ad73845555bcc92bd1728b1/internal/servicelog/template.go#L9
https://github.com/openshift/osdctl/blob/master/cmd/servicelog/post.go#L30

The reason adding a dummy key into the json is that json doesn't support comments natively.

I would like to hear more about your thoughts/concerns.

**Comment by mmazur** [comment]
1. All tags should be on one line and should be close to (directly above?) the summary&description lines, so that one can do a `grep t_network -A 2 -R .` and get usable output from all files. Something like this:

   ```
   $ grep network -A 2 monitoring_stack_broken.json
   "tags": [ "t_network", "t_config" ],
   "summary": "Platform component monitoring accessed by non-Red Hat SRE user",
   "description": "A workload or user on your system has accessed or modified the configuration of the cluster monitoring stack, which is the responsibility of Red Hat SRE. Changes to the cluster-monitoring-config in the openshift-monitoring namespace can interfere with Red Hat's ability to monitor the cluster, and can endanger SLAs. Please refer to https://docs.openshift.com/dedicated/osd_architecture/osd_policy/policy-responsibility-matrix.html.",
   ```
2. Why prefix with "t_"?
3. For this to have a chance of becoming widely-used, it needs its UX tested. Have you tested how it works using github's repo search?

**Comment by mmazur** [comment]
I've tried getting those tags tested using GH's search, but I can't even get [index those jsons](https://github.com/mmazur/mn-test/search?q=ingress). :(

**Comment by feichashao** [comment]
@mmazur Thanks for reviewing!

> All tags should be on one line and should be close to (directly above?) the summary&description lines, so that one can do a grep t_network -A 2 -R . and get usable output from all files. Something like this:

grep is a good point. I was using jq to manipulate the json, I can check if there's an easy way to put them in one line. OSD-13047 mentioned some handy jq functions.


> Why prefix with "t_"?
Because github search or grep matches strings. So it we want it to explicitly search a tag but not a keyword in the content, we add a t_ prefix in the search.   eg, if I want to explicitly search a network tag, search t_network. If I want to search every SL contains a keyword "network", search "network".

> I've tried getting those tags tested using GH's search, but I can't even get [index those jsons](https://github.com/mmazur/mn-test/search?q=ingress). :(

It may take 7 days for github to build the indices :( 
But for this SL template case, as this repo is not changing frequently, having 7 days to build search index should not be a big problem.

**Comment by mmazur** [comment]
Github did eventually index my copy of the repo, so it's possible to test how various tags show up in github search.

- The tags need to be on a single line both for grep and for github search to work properly.
- I've checked the how the `t_` prefix shows up and agree it's better to have it on tags.
- My repo got eventually indexed, so it works, just on a delay. To that effect I've pushed [this commit](https://github.com/mmazur/mn-test/commit/b4ccd05165e8d36fd6980c28a138402e39d722e1) to test where tags should be placed in the json files vs how they show in github search. By this time tomorrow this should be indexed and testable, so we'll have a final answer.

**Comment by mmazur** [comment]
And it appears github changed its search such that it now shows [zero context lines for json files](https://github.com/search?q=repo%3Ammazur%2Fmn-test+t_network&type=code), which made all of my testing thus far pointless :(

**Comment by feichashao** [comment]
Hi @rh-wadhwani , could you approve this?

**Pull request merged**
