### PR TITLE
Add message for misconfigured BYO VPC

### PR DESCRIPTION
**Pull request by fahlmant**

### CODE REVIEW

**Review by jonquilwilliams — COMMENTED** [review]
Suggest changing to: "Error: {$ERROR}. The cluster installation is blocked due to a misconfigured AWS VPC. Correct the error and try creating the cluster again. For help with AWS VPC errors, see <link to AWS VPC docs>."

**Comment by fahlmant** [comment]
What document would you recommend to link them to?

**Comment by jonquilwilliams** [comment]
@fahlmant - I looked at their site, but am not sure what section applies to this. If you're not sure either, maybe just direct them to the general AWS VPC docs page? https://docs.aws.amazon.com/vpc/index.html

**Comment by fahlmant** [comment]
The error that originally spurned this PR was a misconfiguration specific to how OCP would use the VPC.

**Comment by jonquilwilliams** [comment]
Then probably give them this link: https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-vpc.html

Or no link at all, if this one doesn't make sense.

**Comment by cblecker** [comment]
/approve cancel

Test comment to check bot aliveness.. please disregard :)

**Pull request closed without merging**
