### PR TITLE
Add Cluster violation silence notification

### PR DESCRIPTION
**Pull request by iamkirkbater**

### CODE REVIEW

**Comment by aweiteka** [comment]
`Please contact Red Hat Support for further guidance.` is in our email template

**Comment by aweiteka** [comment]
I'd prefer to use a more permanent link like https://docs.openshift.com/dedicated/osd_policy/policy-responsibility-matrix.html than the direct appendix 4 link

**Comment by aweiteka** [comment]
Let's use this existing one https://github.com/openshift/managed-notifications/blob/master/osd/generic_customer_support_case_notification.json

**Comment by T0MASD** [comment]
@iamkirkbater should this PR be closed?

**Pull request closed without merging**
